language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t Chabilkansal/react-test -f ./Client/Dockerfile.dev ./Client

scripts:
  - docker run -e CI=true Chabilkansal/react-test npm run test

after_success:
  - docker build -t Chabilkansal/multi-client ./Client
  - docker build -t Chabilkansal/multi-nginx ./nginx
  - docker build -t Chabilkansal/multi-server ./server
  - docker build -t Chabilkansal/multi-worker ./worker